name: recalculate-activity-points
run-name: ${{ github.actor }} Recalculating Activity Points
on: workflow_dispatch
jobs:
  recalculate-points:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies, Prepare Directories
        run: ./setupEnv.sh && mkdir -p /tmp/activityAccountant

      - name: Generate Credentials File
        with: credential_content: ${{secrets.GOOGLE_DRIVE_SERVICE_CREDENTIALS_JSON}}
        run: echo "$credential_content" > /tmp/activityAccountant/credentials.json

      - name: Download Input Files
        run: GOOGLE_APPLICATION_CREDENTIALS="/tmp/activityAccountant/credentials.json python3 src/googleDriveClient.py

    
      
