name: recalculate-activity-points
run-name: ${{ github.actor }} Recalculating Activity Points
on: workflow_dispatch
jobs:
  recalculate-points:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./setupEnv.sh
      
